from settings import driver,url
import time
driver.get("https://demo.actitime.com/login.do")
driver.maximize_window()
driver.minimize_window()
driver.fullscreen_window()
driver.back()
driver.forward()
driver.refresh()
print(driver.title)
print(driver.current_url)
print(driver.name)
pos = driver.get_window_position()
print("position is : ",pos)
size = driver.get_window_size()
print("size is : ",size)
rect = driver.get_window_rect()
print("rect is : ",rect)
driver.set_window_position(30,40)
time.sleep(2)
driver.set_window_size(1000,500)
time.sleep(2)
driver.set_window_rect(50,50,800,300)
time.sleep(2)
print(driver.page_source)
driver.set_page_load_timeout(10)
driver.close()
driver.quit()

